### ISSUE TITLE
你没有实现呀，有思路吗？

### ISSUE THREAD

**Issue by honchy** [hufeng/node-jsonrpc-dubbo#1]
你没有实现呀，有思路吗？

**Comment by kazaff** [comment]
这个项目应该试图完成一个基于node语言的dubbo客户端，也就是说需要去连接zk注册中心来根据dubbo的url机制完成服务发现，在node端做一定的负载算法等操作，并选择一种dubbo的通信协议，并根据该协议的数据包结构进行数据的编解码，至于数据类型，我猜应该使用dubbo的泛型接口吧~

**Comment by hufeng** [comment]
基本的功能都写完了，目前只支持json-rpc协议。
